" vim config paths
set runtimepath+=$HOME/.config/vim
set viminfo+=n~/.config/vim/viminfo

syntax on

set shiftwidth=4
set smarttab
set tabstop=4
set expandtab

" Hybrid line numbers
set number relativenumber

" Use system clipboard
set clipboard=unnamed
